server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: emp-service
          uri: lb://emp-service
          predicates:
            - Path=/user/**

        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
